---
instance_groups:
- name: access
  jobs:
  - name: ssh_proxy
    release: diego
    properties:
      enable_consul_service_registration: false
      loggregator:
        use_v2_api: true
        ca_cert: (( grab meta.certs.loggregator.ca ))
        cert: (( grab meta.certs.loggregator.metron.server.cert ))
        key: (( grab meta.certs.loggregator.metron.server.key ))
      diego:
        ssl:
          skip_cert_verify: (( grab params.skip_ssl_validation ))
        ssh_proxy:
          bbs:
            .: (( inject meta.certs.diego.bbs.client ))
            require_ssl: true
            ca_cert: (( grab meta.certs.diego.ca ))
          enable_cf_auth: true
          disable_healthcheck_server: true
          host_key: (( vault meta.vault "/ssh_proxy/host_key:private" ))
          uaa_secret: (( grab meta.uaa.ssh_proxy_secret ))
          uaa:
            port: (( grab meta.uaa.ssl_port ))
            ca_cert: (( grab meta.certs.uaa.ca ))


  - name: file_server
    release: diego
    properties:
      bpm:
        enabled: true
      logging:
        format:
          timestamp: "rfc3339"
      loggregator:
        use_v2_api: true
        ca_cert: (( grab meta.certs.loggregator.ca ))
        cert: (( grab meta.certs.loggregator.metron.server.cert ))
        key: (( grab meta.certs.loggregator.metron.server.key ))
