releases:
- name:    binary-buildpack
  version: "1.0.32"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/binary-buildpack-release?v=" releases.binary-buildpack.version ))
  sha1:    5ab3b7e685ca18a47d0b4a16d0e3b60832b0a393

- name:    dotnet-core-buildpack
  version: "2.2.12"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/dotnet-core-buildpack-release?v=" releases.dotnet-core-buildpack.version ))
  sha1:    ba037a288209a1d088ec717a006164f2baa99a7b

- name:    go-buildpack
  version: "1.8.39"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/go-buildpack-release?v=" releases.go-buildpack.version ))
  sha1:    717ef8bf2032ca9aa814fe6f49070778e5bbb0a3

- name:    java-buildpack
  version: "4.19"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/java-buildpack-release?v=" releases.java-buildpack.version ))
  sha1:    7099d188d47517f0cb2725aa71b540605e4058b6

- name:    nginx-buildpack
  version: "1.0.13"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/nginx-buildpack-release?v=" releases.nginx-buildpack.version ))
  sha1:    a9f9464fac46617b415285e1f94ad6c36e55b2b8

- name:    nodejs-buildpack
  version: "1.6.51"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/nodejs-buildpack-release?v=" releases.nodejs-buildpack.version ))
  sha1:    a8104e1769cce2ba5a7ed9c775c9e046df21edc6

- name:    php-buildpack
  version: "4.3.77"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/php-buildpack-release?v=" releases.php-buildpack.version ))
  sha1:    06359e8512b40f8bc81300aca08e0a7ba77bc1af

- name:    python-buildpack
  version: "1.6.34"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/python-buildpack-release?v=" releases.python-buildpack.version ))
  sha1:    941778b5b6fc0b60b5cba95315ae8f18aacdae65

- name:    r-buildpack
  version: "1.0.10"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/r-buildpack-release?v=" releases.r-buildpack.version ))
  sha1:    e7f40b13293c5f0b68d306729dabb54e1ee3c765

- name:    ruby-buildpack
  version: "1.7.40"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/ruby-buildpack-release?v=" releases.ruby-buildpack.version ))
  sha1:    dd28168efe9efc463de830855cbab704b8f8b99e

- name:    staticfile-buildpack
  version: "1.4.43"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/staticfile-buildpack-release?v=" releases.staticfile-buildpack.version ))
  sha1:    0f47a7035645bce994f64a5021f930a5eb246caf
