---

meta:
  cc:
    volume_services_enabled: true

instance_groups:
  - name: cell
    jobs:
      - (( append ))
      - name: nfsv3driver
        release: nfs-volume

releases:
  - name:    nfs-volume
    version: "1.0.7"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry-incubator/nfs-volume-release?v=" releases.nfs-volume.version ))
    sha1:    f609a25be32e1fc634e683cc3a89c0aaad1e70f0
